# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    configs:
        my_config:
            toolbar: [ ["Source", "-", "Save"], "/", ["Anchor"], "/", ["Maximize"] ]
            uiColor: "#000000"
            # filebrowserUploadRoute: "my_route"
            extraPlugins: 'wordcount'

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
